### PR TITLE
Added vanilla injection

### PR DESCRIPTION
**Pull request by glebiller**
In order to have a base reference to compare all frameworks, I have added simple object creation with native constructor.

### CODE REVIEW

**Comment by greenlaw110** [comment]
Thank you very much! Can you please catch up the master changes and submit your pull request again? Much appreciated!

**Comment by greenlaw110** [comment]
I think there is a problem with vanilla container: you made it serves as like `A` is a Singleton. But it is not the case actually, as per JSR330, only bean class or factory method with annotation `@javax.inject.Singleton` shall be treated as singleton. Otherwise, it shall construct the new instance as per request. This is also true for all other containers that participates the test. 

I've added identity test case in the [unit test](https://github.com/greenlaw110/di-benchmark/blob/master/src/test/java/BenchmarkTest.java#L48) to specifically make sure the beand returned by two different inject requests is not the same object

**Comment by glebiller** [comment]
I made some changes to be compliant with JSR330.
Corrected the conflicts for this PR too.

**Comment by greenlaw110** [comment]
Thanks for the contribution! I've merged and updated the `README.md` file with vanilla benchmark data

**Pull request merged**
